name: BROWN BLOGS
favicon: null
layout_spectrum: 0.75647
typography_spectrum: 0.24803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#122013'
    - '#3e4647'
    - '#8a979d'
    - '#cbbbb0'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
